# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
require 'namey'

courses = ["Actuadores Electricos - Comp. Secc.383",
"Acuerdos Comerciales",
"Acumulad. Y Vehículos Electr.
Admin. De Ventas",
"Admin. De Ventas - Comp. Con Sección 165 De Ceutec",
"Administ. De Proyectos",
"Administracion De Obras",
"Administración I",
"Administración Ii",
"Admon. De Inversiones",
"Admon. De La Produccion",
"Admon. De La Tecnologia",
"Admon. Del Credito",
"Admon. Empre. Internacionales",
"Admon. Operaciones I",
"Admon. Y Aplicaciones De Redes",
"Agresión Y Defensa - Laboratorio Miercoles 7:00 A.M. A 09:50 A.M.
Ajedrez - Intesiva De 8:00 Am - 1:00 Pm. En Reczen",
"Aleman I",
"Aleman Ii",
"Algebra",
"Algebra - Ccss Y Salud",
"Algebra - Ingenierías",
"Algebra - Solo Para Ingenierias",
"Algebra Lineal",
"Anal. Y Dis. De Sistemas I",
"Anali. Hiperestatico I",
"Anali. Hiperestatico Ii",
"Analisis Contable I",
"Analisis Contable I - Sección Compartida Con 26 - Ceutec Próceres, Lp608",
"Analisis Contable Ii",
"Analisis De Algoritmos - Viernes 7:00-9:40, Sábados 8:00-10:40 - Aula De Teledocencia",
"Analisis De Sistemas",
"Analisis Numerico",
"Anatomia Y Fisiologia I",
"Anatomía Cabeza Y Cuello",
"Análisis Y Opt. Ener. Instal.
Apreciacion Literaria",
"Apreciacion Musical",
"Arcview - 06/310",
"Artes Finales - Lab. De Computo Mac",
"Aspectos Comerciales",
"Aspectos Operativos",
"Auditoria De Proyectos",
"Bases Biol. Comp. Hum. I",
"Bases Biol. Comp. Hum. Ii",
"Bienes Raices",
"Bienes Y Derechos Reales",
"Bioestadística",
"Biofísica - Laboratorio Jueves 11:30 A.M. A 12:50 P.M.
Biofísica - Laboratorio Jueves 7:00 Am",
"Biologia",
"Bioquímica De La Nutrición",
"Bioética",
"Brand Design - Taller De Diseño 8:30Am-11:10Am",
"Cad 2D",
"Cad 3D",
"Calculo I Dif. Geo. An.
Calculo I Integr.
Calculo I Integr. - Compartida Con Ceutec Sección 760",
"Calculo Ii Geo. Analiti",
"Calculo Para Cc. Sociales",
"Campañas De Divulgacion - Aula Recurso Audiovisual",
"Cinematografia Documental - Aula Recurso Audiovisual",
"Circuitos Electricos I",
"Circuitos Electricos Ii",
"Cirugía General I",
"Cirugía General I -
Coaching Y Mentoring",
"Comercio Electronico",
"Compiladores I",
"Comport. Del Consumidor",
"Comport. Del Consumidor - Clase Internacional",
"Comporta. Humano En Las Orga.
Comput. Aplic. Al Diseño Graf. - Lab. Computo",
"Comput. Aplic. Al Diseño Graf. - Laboratorio De Cómputo",
"Comunic. Para La Diversidad",
"Comunicacion - Termina A Las 4:00 Pm",
"Comunicacion Grafica I - Lab. Computo Compartida 213",
"Comunicacion Grafica Ii - Lab. De Computo, Compartida 223",
"Comunicación Efectiva",
"Comunicación Oral Y Escrita",
"Conservacion Monumentos",
"Constraints",
"Consultoria Empresarial - Clase Intensiva Viernes",
"Conta. Toma Decisiones",
"Contabilidad Bancaria",
"Contabilidad De Costos I",
"Control De Procesos En La P.
Control De Versiones Y Fra.
Control Digital",
"Control Gestión Total",
"Convers. Y Oratoria (Ing. Av)
Conversation And Grammar Ii",
"Cooperac. Internac. Y Desarr. - Clase Orientación Diplomacia",
"Coordinación",
"Coordinación - Coordinación De Natación",
"Coordinación - Coordinación",
"Coordinación - Días Viernes 08:00 A.M A 12:00 M",
"Creatividad Publicit. - 05/601",
"Creatividad Publicitaria - Aula Recurso Audiovisual, Plan Viejo",
"Cálculo I - Compartida Con La 1603",
"Cálculo Ii - Compartida Con La 1611",
"Defensa Personal - Polid",
"Definicion E Ide. P. S.Sigma",
"Der. Internac. Público - Comp. Secc. 316 Unitec",
"Derecho Administrativo I",
"Derecho Administrativo Ii",
"Derecho Agrario - Comp. Ceutec Secc 494",
"Derecho Ambiental - Cupo Compartido Con Ceutec Prado Sec 505",
"Derecho Banc. Y Oper. Credito - 01/208",
"Derecho Comercial Internac.
Derecho Constitucional - Clase De Derecho Y Relaciones Int.
Derecho Constitucional - Comp. Ceutec Secc. 419",
"Derecho De Seguros",
"Derecho De Sucesiones",
"Derecho Diplomatico Y Consular",
"Derecho Economico - Electiva De Formación Derecho Empresarial",
"Derecho Empresarial",
"Derecho Fiscal - Clase Semestral",
"Derecho Individual Del Trabajo",
"Derecho Internac. Privado",
"Derecho Internacional I",
"Derecho Internacional Ii - Comp. Seccion 330 Unitec",
"Derecho Maritimo Y Aeronautico - Clase Compartida Con Ceutec Sec. 525",
"Derecho Mercantil Avanzado",
"Derecho Mercantil Avanzado - Comp. Ceutec Secc. 491",
"Derecho Mercantil I",
"Derecho Mercantil I - Comp. Ceutec Secc 474",
"Derecho Mercantil Ii",
"Derecho Notarial I",
"Derecho Notarial Ii",
"Derecho Notarial Ii - Cupo Comp. Con Ceutec Prado Sec. 514",
"Derecho Penal I",
"Derecho Penal Ii",
"Derecho Procesal Civil Ii",
"Derecho Romano",
"Derecho Sindical Del Trabajo",
"Derecho Sindical Del Trabajo - C Omp. Ceutec Secc 470",
"Derechos Humanos",
"Derechos Humanos - Cupo Comr. Ceutec Prado Sec 483",
"Desa. Y Eval. Del Desempeño - Comp. Con Sección 399 Ceutec",
"Desarrollo Organizac.
Desarrollo Organizac. - Comp. Con Sección 238 Ceutec",
"Desarrollo Prods Export",
"Desarrollo Prods Export - Comp. Ceutec Secc 242",
"Dibujo - Aula De Dibujo",
"Dibujo Inge. Civil - Compartida Con Sección 510",
"Dibujo Para Ingeniería - Compartida Con Sección 509",
"Dibujo Tecnico",
"Diplomacia Pública",
"Dis Y Prod Etiq, Env Y Emp - 06/102",
"Diseño Arquitectonico Ii - Modalidad Presencial Horario 2 Días",
"Diseño Arquitectonico Iii - Modalidad Presencial Horario 2 Días",
"Diseño Arquitectonico V - Modalidad Presencial Horario 2 Días",
"Diseño Arquitectonico Vii - Modalidad Presencial Horario 2 Días",
"Diseño Arquitectonico Viii - Modalidad Presencial Horario 2 Días",
"Diseño De Cimentaciones",
"Diseño De Sistemas Logicos - Compartida Sección 647: Diseño Lógico Digital",
"Diseño Editorial - Compartida S. 683 Ceutec Ca",
"Diseño Estructural I",
"Diseño Estructural Ii",
"Diseño Logico Digital - Compartida Sección 598: Diseño Sistemas Lógicos",
"Diseño Mecatronico - Asignatura Doble Titulación Claudio Hernández",
"Diseño Y Ecología Ii - Modalidad Presencial Horario 2 Días",
"Ecologia",
"Economia Del Turismo",
"Economia Gerencial",
"Economia Internac.
Economia Internac. - Sección Comp. Con Sección 249 De Ceutec",
"Ecuaciones Diferenc.
Ecuaciones Diferenc. - Impartida En Ceutec, Sección 556, Lp/711, Martes Y Jueves",
"Edicion De Imagen Digital",
"Edicion De Impresos - Lab. De Computo Comp. Secc. 253",
"Edición Medios Impr. Y Digit. - Lab. De Computo",
"Electronica De Potencia",
"Electronica I",
"Electronica Ii",
"Elementos De Estatica",
"Equipos De Alto Rendimiento",
"Equipos De Laboratorio",
"Equipos De Oxigenoterapia",
"Equipos De Soporte De Vida",
"Equipos Sala De Operaciones",
"Espanol",
"Espanol - Comp. Secc. 153",
"Est. Vida, Salud Y Medioamb. - Viernes De 2:20 P.M. A 5:00 P.M.
Estadist. Matematica I",
"Estadist. Matematica Ii",
"Estadistica I",
"Estadistica Ii",
"Estadística Social Aplicada -
Estadística Social Aplicada - Comp. Ceutec Secc. 797",
"Estatica",
"Estrateg.De Merc. Inter - 01/303",
"Estrategia Gerencial",
"Estrategia Gerencial - Comp. Ceutec Secc 213 Centroamerica",
"Estrategia Gerencial - Comp. Con Ceutec Sección 210",
"Estrategia Gerencial - Comp. Con Ceutec Sección 216",
"Estrategia Gerencial - Compartida Con Sección 207 - Ceutec Lp/604.
Estruct. Concreto I",
"Estruct. De Concreto Ii",
"Estructuras I",
"Estructuras Iii",
"Etica Profesional",
"Etica Psicologica - Plan Viejo Comp. Unitec Secc 554",
"Evaluacion De Proyectos",
"Expresion Oral",
"Expresion Oral - Aula Recurso Audiovisual",
"Farmacología General - Laboratorio Lunes 2:20 P.M. A 6:30 P.M.
Filosofia",
"Filosofía Del Derecho",
"Filosofía Del Derecho - Cupo Compartido Con Ceutec Ca Sec 525",
"Filosofía Política",
"Finanzas Internacional",
"Fisica I",
"Fisica Ii",
"Fisica Iii",
"Fisica Iv",
"Fisiología General",
"Fisiopatología General",
"Formulac Y Gest De Proye",
"Formulación Y Eval. Proyectos",
"Fotografia - 05/301",
"Fotografia - Aula Edificio 5",
"Fotografia Comercial",
"Fotografia Comercial - Aula Edificio 5 Comp Secc 249",
"Fotografia Comercial - Aula Edificio 5 Comp. Secc. 248",
"Fotografia De Retrato",
"Fotografia Digital",
"Frances I",
"Frances Ii",
"Frances Iii",
"Frances Iv",
"Fund. Tec. Med. Audiov. - Modalidad Tutoría",
"Fundam. Creatividad Publicit. - 05/601",
"Fundam. Teoria De Comun - Aula Recurso Audiovisual Comp. Secc 98",
"Física Médica - Laboratorio Jueves 10:10 A.M. A 11:30 A.M.
Gener. De Empresas I",
"Gener. De Empresas I -
Gener. De Empresas I - 03/205",
"Gener. De Empresas I - Clase Internacional",
"Gener. De Empresas I - Cupo Compartido Ceutec Prado Sec 274",
"Gener. De Empresas I - Comp. Con Ceutec Sección 274",
"Gener. De Empresas Ii",
"Gener. De Empresas Ii - 01/401",
"Gener. De Empresas Ii - Comp. Con Ceutec Sección 801",
"Generac. De Empresas En Salud",
"Generacion De Ideas M.N.
Genética - Laboratorio Martes 2:20 Pm A 6:30 Pm",
"Genética - Laboratorio Viernes 2:20 P.M. A 6:30 P.M.
Geogr. Polit. Econ. Y Social",
"Geografia Turistica Nacional",
"Geologia",
"Geometria Trigonometria",
"Ger.Recursos Humanos I",
"Ger.Recursos Humanos Ii",
"Gerencia Financiera I",
"Gerencia Financiera I - Comp. Ceutec Secc 448",
"Gerencia Financiera I - Comp. Ceutec Secc. 448",
"Gerencia Financiera Ii",
"Gerencia Financiera Iii",
"Gestion De Calidad",
"Gestion De Calidad - Comp. Secc. 403",
"Gestion De Calidad - Comp. Secc. 405",
"Gestion De Compras - Matrícula Con Autorización. Requisito: Log401 Logística I",
"Gestion De Imag. Publica - Comp. Secc 344 Unitec",
"Gestion Del Talento Humano I",
"Gestion Del Talento Humano Ii",
"Gestion Hospitalaria",
"Gestion Negoc. Estrateg",
"Gestión De Datos En Óptica",
"Gestión De Eventos Y Protocolo - Compartida Con Rel103 Secc 340",
"Gestión De Serv. En Salud - Jueves De 10:10 A 12:50 P.M.; Viernes 08:30 A.M. A 09:50 A.M",
"Global Market",
"Guion Med. Audiov. - Aula Recurso Audiovisual",
"Herr. Y Técn. Adm. Proy.
Hidrologia",
"Hist. Polit. Soc. Y Cont. A.L",
"Historia Arqui. Urbanismo Ii",
"Historia Arqui. Urbanismo Iv",
"Historia De Honduras",
"Historia Del Arte",
"Historia Poli.Y Soc. Contempo",
"Historia Y An. Del Arte Visual - Aula Recurso Audiovisual",
"Identidad Visual Corporativa - Lab. Computo Compartida Secc 222",
"Iluminacion",
"Imagen Corporativa",
"Imagen Corporativa - 01/110",
"Imagenologia",
"Infracciones Tributarias",
"Ingenieria Ambiental",
"Ingenieria De Control",
"Ingenieria De Metodos Avanzad. - Matrícula Con Autorización. Requisito: Ind301 Ing. De Método",
"Ingenieria De Software",
"Ingenieria De Software - Compartida Ceutec Sección 722 - Proceres - Lp/501",
"Ingenieria Economica",
"Ingenieria Hidraulica I",
"Ingenieria Hidraulica Ii",
"Ingenieria Sanitaria I",
"Ingenieria Sanitaria Ii",
"Ingles I",
"Ingles I - Compartida Con La 531 De Ceutec Ca",
"Ingles I - Compartida Con La Seccion 582 De Ceutec Proceres",
"Ingles I - Especial De Terapia Física, Materia De 5V, Impartirá 2Hr",
"Ingles Ii",
"Ingles Iii",
"Ingles Iii - Compartida Con La 605 De Ceutec Ca",
"Ingles Iii - Compartida Con La 614 De Ceutec Ca",
"Ingles Iii - Compartida Con La 658 De Ceutec Ca",
"Ingles Iv",
"Ingles Iv - Clase Compartida Con La 308 De Ceutec Ca",
"Ingles V",
"Ingles Vi",
"Ingles Vi - Compartida Con La 659 De Ceutec Ca",
"Ingles Vii",
"Ingles Viii",
"Innov. Desa. Produc.
Instal. Hospitalarias I",
"Instal. Hospitalarias Iii",
"Instalacion Edificaciones Ii -
Instalaciones",
"Instalaciones Eléctricas - 03/205",
"Instituc. Y Organ. Internac.
Inteligencia Emocional",
"Interacción Fármaco-Nutrim. - Lunes 8:30 -9:50, Martes 8:30 -10:10; Lab. Miercoles 7:00 Am",
"Intro. A La Mecatrónica",
"Intro. Al Estudio Del Derecho",
"Intro. Inge. Industrial",
"Intro. Medios Audivisu - Aula Recurso Audiovisual",
"Intro. Nutrición Y Dietética",
"Intro. Telecomunicaciones",
"Intro. Teoría Relac. Intern. - Clase Se Imparte Tres Días A La Semana",
"Introd. A La Comunicación - Aula Recurso Audiovisual, Compartida Con S. 264",
"Introd. Al Diseño Grafico - Taller De Diseño.
Introd. Ciencia Política - 01/106",
"Introd.Teoria Monetaria",
"Introduc. Diseño Arquitect",
"Introduccion A La Computa",
"Introduccion A Seis Sigma",
"Introduccion Al Algebra",
"Introduccion Al Algebra - Ccss",
"Introduccion Al Algebra - Ingenierías Y Salud",
"Introduccion Al Diseño",
"Introduccion Analisis Financ.
Introduccion Analisis Financ. - Comp. Ceutec Secc. 693",
"Introduccion Ing. Biomedica",
"Introducción A La Economía",
"Introducción A La Psicología",
"Inves. Oper. Ingenieria - Comp. Secc. 409",
"Inves. Oper. Ingenieria - Comp. Secc. 411",
"Invest. De Mercados I",
"Invest. De Mercados I - Clase Comp. Ceutec Sección 802",
"Invest. De Mercados Ii - Comp. Con Ceutec Sección 805",
"Investigacion Operaciones - Comp. Secc. 410",
"Investigacion Operaciones - Comp. Secc. 412",
"Investigación - Docente Atiende A Los Estudiantes De La Fcs En Investigación",
"Italiano I",
"Italiano Ii",
"Italiano Iii",
"Italiano Iii - Sección Compartida Con 860 Ceutec Ca",
"Italiano Iv",
"Italiano Iv - Sección Compartida Con 865 De Ceutec",
"Lab. De Circuitos Y Mediciones - Lab. De Circuitos Electricos Ii",
"Lab. De Circuitos Y Mediciones - Secc2_Lab. De Circuitos Electricos I",
"Lab. De Circuitos Y Mediciones - Seccion1_Lab De Circuitos Electricos I",
"Lab. De Concreto - Inscripción Adicional Lab Civil",
"Lab. De Control Automatico - Lab. De Control Digital",
"Lab. De Diseño Sistem. Logicos - Lab. De Diseño De Sistemas Logicos",
"Lab. De Diseño Sistem. Logicos - Secc2_Lab De Diseño Lógico Digital & Diseño Sist. Lógicos",
"Lab. De Electronica - Lab. De Electronica Ii",
"Lab. De Instrument. Y Medicion - Lab. De Electronica I",
"Lab. De Microprocesadores I",
"Lab. De Sistemas De Comunicac. - Lab. De Redes De Comunicacion",
"Lab. De Sistemas Digitales - Lab. De Sistemas De Comunicacion",
"Lab. De Topografia I",
"Lab. De Topografia Ii",
"Lab. De Vias De Comunic - Inscripción Adicional En Lab Civil",
"Lab. Programacion I",
"Lab. Programacion Ii",
"Lab. Programacion Iii",
"Laboratorio Animacion - Lab. Computo 7Am-10Am",
"Laboratorio Spss",
"Legis. Inst Financieras - Clase De Finanzas",
"Legis. Inst Financieras - Comp. Con Ceutec Sección 464",
"Legislacion Arquitectonica - Matrícula Con Autorización Fia *Requesito Arq427",
"Legislacion Comercio Electron. - Clase Tutorial",
"Legislacion Comercio Electron. - Sección Compartida Con 521 Ceutec",
"Legislacion Nego. Interna. - Clase De Mercadotecnia Y Negocios Int.
Lenguajes Programacion",
"Lentes Y Enfermedades Oculares",
"Literatura Mundial (Ing. Av)
Literatura Mundial (Ing. Av) - Compartida Con La 879 De Ceutec Proceres",
"Local Culture A",
"Logistica I",
"Logistica Ii",
"Lógica Jurídica",
"Macroeconomia",
"Macroeconomia - 03/206",
"Macroeconomia - Comp. Ceutec Secc 808",
"Macroeconomia - Comp. Ceutec Secc. 810",
"Macrovisibility - Aula Edificio 2 4To Piso De 1:00Pm A 3:40Pm",
"Mandarin I",
"Mandarin Ii",
"Mandarin Iii",
"Mandarin Iv",
"Manuf. Automatizada I - Comp. Secc 595",
"Matematica Financiera",
"Matematicas Discretas",
"Materiales Dentales - Lab Viernes 7 - 9:50 Am",
"Mecanica De Fluidos",
"Mecanica De Suelos Ii",
"Mecanismos",
"Medicion Estadistica De Pro.
Merc. E Intermed. Financieros",
"Merc. E Intermed. Financieros - Comp. Con Sección 458 De Ceutec",
"Mercadotecnia Bancaria",
"Mercadotecnia I",
"Mercadotecnia I - Clase Internacional",
"Mercadotecnia Ii",
"Mercadotecnia Iii",
"Metodologia Del Diseño - Aula Edificio 5",
"Metodología De Investigación",
"Metodología De Investigación - Viernes De 2:20 Pm A 5:00 P.M.
Metodología Investigac.
Metodología Investigac. - Clase Internacional",
"Metodos Numericos",
"Metrol. Normal",
"Micro. Higie Inocu. Alim.
Microbiologia Industrial - Matrícula Con Autorización Requisito:Bio302 Químicaalimentos",
"Microbiología De Los Alimentos",
"Microbiología De Los Alimentos - Laboratorio Pendiente",
"Microbiología E Inmunología - Laboratorio Martes 2:20 P.M. A 6:30 P.M.
Microbiología E Inmunología - Laboratorio Viernes 2:20 P.M. A 6:30 P.M.
Microeconomia",
"Microeconomia - 03/206",
"Microprocesadores I",
"Modela. Procesos Industriales - Impartida En Ceutec, Sección 651, 6:00 Pm Lp/L05 Días 13",
"Morfofisiología Bucodental Ii - Martes, Jueves Y Viernes 2.:20 - 6:30",
"Morfología General",
"Multimedia - Lab. De Computo Comp.
Máquinas Herramientas",
"Natacion - En Polideportivo",
"Negociac. Solución Conflictos",
"Negociacion - 01/106",
"Negociacion - Cupo Compartifo Ceutec Prado Sec 836",
"Negociación - Clase Comienza 6:40Am",
"Negocios Internacionales",
"Negocios Internacionales - Comp. Ceutec Secc 819",
"Negocios Internacionales - Sección Compartida Con 819 En Ceutec Próceres",
"Negocios Internacionales - Sección Compartida Con 818 En Ceutec Ca",
"Nutric. Embarazo Y Lactancia - Laboratorio Viernes 7:00 Am Cesamo Los Pinos",
"Obligaciones Y Contratos I",
"Obligaciones Y Contratos I - Sección 465 Comaprtida Con Ceutec Proceres",
"Obligaciones Y Contratos Ii",
"Obligaciones Y Contratos Ii - Comp. Ceutec Secc 467",
"Oclusión - Lab Viernes 7:00 - 9:50",
"Odontología Terapéutica - Lab Jueves 8:30 A 11:30",
"Ofimatica I",
"Ofimatica I - Alumnos Con Laptop",
"Ofimatica I - Alumnos Con Su Laptop",
"Ofimatica I - Alumnos Sin Laptop",
"Ofimatica Ii",
"Ofimatica Ii - Alumnos Con Laptop",
"Ofimatica Ii - Alumnos Sin Laptop",
"Ofimatica Iii",
"Ofimatica Iii - Alumnos Sin Laptop",
"Ofimatica Iii - Alumnos Con Laptop",
"Ofimática Avanzada",
"Ofimática Avanzada - Alumnos Sin Laptop",
"Opera Del Comer Ext",
"Optometría Cien. Visión",
"Organiz. De Archivos",
"Paisajismo",
"Peq Empr Y Desa De Franq",
"Percepción Y Represen Iii - Modalidad Presencial Horario 2 Días",
"Percepción Y Representación I - Mod. Presencial Horario 2 Días",
"Periodoncia I - Lunes A Jueves 3:40 - 6:30",
"Personas Y Familia",
"Plan. Estrat. Toma De Decisi.
Plan. Y Control Mercadotec.
Plan. Y Control Mercadotec. - Comp. Con Ceutec Sección 822",
"Planeac Estrat. De Rr Hh - Comp. Con Ceutec Sección 396",
"Planificacion De Medios - Aula Recurso Audiovisual",
"Planificacion Urbana Ii - Modalidad Presencial Horario 2 Días",
"Planificación Y Estrat. Medios - Aula Recurso Audiovisual, Compartida 229",
"Política Exterior De Honduras",
"Portugues I",
"Portugues Ii",
"Portugues Iii",
"Portugues Iii - Clase Intensiva De 8:00 Am- 1:00 Pm",
"Portugues Iv",
"Practica Procesal Civil",
"Practica Profes. - Con Autorización Jefe Académico",
"Practica Profes. - Sección Para Disney",
"Practica Profesional",
"Practica Profesional - Comp Secc 741",
"Practica Profesional - Con Autorizacion",
"Practica Profesional - Con Autorizacion. Compartida Con Sección 835",
"Practica Profesional - Con Autorización Jefe Académico. Práctica Prof Pública",
"Practica Profesional - Disney Con Autorizacion",
"Practica Profesional - Disney Con Autorización",
"Practica Profesional - Matricula Practica Privada De Derecho. Con Autorización",
"Practica Profesional - Matrícula Con Autorización. Comp. Secc. 416",
"Practica Profesional - Pp/Arq",
"Prep. Para El Toefl (Ing. Av)
Preparación Y Conserv. Alim. - Laboratorios Dias Martes Y Miercoles",
"Presupuestos",
"Preventiva Ii - 8:30-11:30 Lab Jueves",
"Proc. Permisos Y Socializ.
Proce. Y Pract. Proc. Laboral",
"Proce. Y Pract. Proc. Laboral - Cupo Compartido Ceutec Prado Sec 510",
"Proce. Y Pract. Proc. Adm.
Proce. Y Pract. Proc. Penal",
"Procesos Biológicos I - Laboratorio Lunes 1:00 P.M. A 05:00 P.M.
Procesos Biológicos I - Laboratorio Miercoles 1:00 A 5:00 P.M.
Procesos Biológicos Ii - Laboratorio Jueves 1.00 P.M. A 5.00 P.M.
Procesos Biológicos Ii - Laboratorio Miercoles 1:00 P.M. A 5:00 P.M",
"Procesos Nutric. Y Metab.
Produc. Publicidad - Aula Edificio 5",
"Produc. Television - Aula Recurso Audiovisual Comp Secc 251",
"Produccion De Artes Graficas - Compartida Sección 680 Ceutec Ca",
"Produccion De Audio",
"Produccion De Noticias - Aula Recursos Audiovisual",
"Producción Audiovisual I - Aula Recurso Audiovisual Comp. Secc 250",
"Producción De Radio En Directo",
"Productividad Y Calidad",
"Productividad Y Calidad - Comp. Secc. 402",
"Productividad Y Calidad - Comp. Secc. 404",
"Productividad Y Calidad - Comp. 148 Ceutec, 7Am, Lp/607, Martes Y Jueves, Próceres",
"Progra. Ingenieria",
"Programacion",
"Programacion - Compartida Ceutec- Seccion - 734 - Proceres Lp/L05",
"Programacion Con Swift",
"Programacion I",
"Programacion Ii",
"Programacion Iii",
"Programacion Iv",
"Promocion Y Negociacion Inver.
Promocion Y Pub. Inter.
Propiedad Intelectual",
"Proyec. Perspe. Sombras Ii - Modalida Presencial Horario 2 Días",
"Proyecto De Graduacion",
"Proyecto De Graduacion - Con Autorizacion",
"Proyecto De Graduacion - Con Autorización De Jefe Académico",
"Proyecto De Graduacion - Mercadotecnia Pura Comp. Secc. 285",
"Proyecto De Graduacion Fase I - Proyecto Graduación Fase I -Compartida Sección 455",
"Proyecto De Graduacion Fase I - Práctica Profesional Fase I",
"Proyecto De Graduacion Fase Ii - Proyecto Graduación Fase Ii - Compartida Sección 455",
"Proyecto De Graduacion Fase Ii - Práctica Profesional Fase Ii Compartida Sección 455",
"Proyecto De Graduación - Con Autorizacion",
"Proyecto De Investigación - Modalidad Tutorial 08:30Am -11:00Am",
"Proyecto Fase I - Comp Secc 741",
"Proyecto Graduacion - Matrícula Con Autorización. Comp. Secc. 415",
"Proyecto Graduacion Fase I - Matrícula Con Autorización Fia",
"Proyecto Graduacion Fase Ii - Matrícula Con Autorización Fia",
"Proyecto I",
"Proyecto I - Comp Secc 784",
"Proyecto I Fase - Compartida Tel593",
"Proyecto Ii",
"Proyecto Ii Fase - Cmopartida Tel592",
"Práct. Clín. Estado Nutric. - Laboratorio Dia Jueves 7:00 Am",
"Práctica Profesional - Con Autorizacion",
"Práctica Profesional - Con Autorización. Compartida Con Sección 558",
"Práctica Profesional - Plan Nuevo Con Autorizacion",
"Práctica Profesional - Viaje Disney",
"Prácticas Médicas I - Centro De Salud 07:00 A 11:30 A.M. Miercoles,Jueves,Viernes",
"Prácticas Médicas Ii - Centro De Salud Viernes 07:00 Am A 12:;50 P.M.
Prácticas Médicas Iii - Jueves 07:00 A.M. A 09:50 A.M.
Prácticas Médicas Iv",
"Psicodiagnostico - Plan Viejo Comp. Secc. 539",
"Psicodiagnóstico I",
"Psicol. Des. Humano I",
"Psicol. Des. Humano Ii",
"Psicologia Del Conflicto - Plan Viejo Tutorial",
"Psicologia Del Diseño",
"Psicologia Deportiva Ii",
"Psicologia Educativa - Plan Viejo Comp. Secc. 559 Unitec",
"Psicologia Hig. Seg. Industri. - Plan Viejo",
"Psicologia Organizacional",
"Psicologia Organizacional - Plan Viejo Comp. Secc 556",
"Psicologia Proces. Sociales - Clase Tutorial",
"Psicologia Social",
"Psicologia Y Ergonomia Empr. - Comp. Con Sección 382 De Ceutec",
"Psicología Comunitaria",
"Psicología Educativa I",
"Psicología Educativa Iii - Clase Tutorial",
"Psicometria I",
"Psicometria Ii",
"Psicometria Iii - Comp. Con Sección 369 De Ceutec",
"Psicometría Iv",
"Psicopatologia - Plan Viejo Comp. Secc. 538",
"Psicopatología I",
"Psiquiatría General - Clase Intensiva De 8:30Am A 11:40Am",
"Publicidad",
"Puentes",
"Quimica General",
"Química De Alimentos - Laboratorio Dia Martes",
"Química Médica I - Laboratorio Juevess 08:30 A.M. A 11:30 A.M",
"Química Médica I - Laboratorio Viernes 07:00 A.M. A 09:50 A.M.
Química Médica I - Viernes 5:00 A 8:00 Pm Sabado 7 A 9:00 A.M Lab 9-12 P.M.
Química Médica Ii - Laboratorio Viernes 09:30 A 11:30 A.M.
Recursos Administrativos",
"Redacc. Para Los Medios - Aula Recursos Audiovisual",
"Redaccion - Aula Recurso Audiovisual Comp.236",
"Redaccion - Aula Recurso Audiovisual Comp Secc 247",
"Redaccion - Aula Recurso Audiovisual Comp. Secc. 246",
"Redaccion - Aula Recurso Audiovisual Secc 235",
"Redacción Académica (Ing. Av)
Redes",
"Redes De Comunicación",
"Redes Industriales",
"Redes Industriales Ii - Comp Secc 386",
"Regulacion Automatica - Comp Secc 795",
"Relaciones Intern. Ii",
"Relaciones Publicas Y Pro - Compartida Con Rel314",
"Resist. De Materiales I",
"Resist. Materiales Ii",
"Retos Y Desafios Fam. Hoy",
"Roomscape -
Salud De La Mujer",
"Salud Infantil",
"Salud Pública",
"Seguridad Computacional",
"Seguridad Computacional - Compartida Ceutec Sección 727 - Proceres Lp/501",
"Seguridad Perimetral En Redes",
"Sem. Politica Economica - 01/307",
"Sem. Politica Economica - 01/406",
"Semiología Y Análisis Del Dis. - Aula Recurso Audiovisual",
"Semiología Y Diagnóstico - Lunes Y Miercoles 2:20 - 6:30",
"Semiotica - Taller De Diseño",
"Sensores Y Actuadores - Comp. Secc. 384",
"Servicio Al Cliente",
"Simulacion Judicial",
"Sist. Gastroint. Y Proc. Met.
Sist. Inform. Turistica",
"Sistema Circulatorio",
"Sistema Endocrino",
"Sistema Gastrointestinal",
"Sistema Genitourinario",
"Sistema Ges. Inocu. De La Al.
Sistema Hematopoyético",
"Sistema Nervioso",
"Sistema Nervioso Y Endocrino",
"Sistema Osteomioarticular",
"Sistema Respiratorio",
"Sistema Tegumentario",
"Sistema Urogenital Y Renal",
"Sistemas De Comunic.
Sistemas De Construccion -
Sistemas De Infor. Geografica",
"Sistemas De Informacion",
"Sistemas De Informacion - Compartida Ceutec - Sección 728 - Centroamerica Ca/504",
"Sistemas De Trans. Turisticos",
"Sistemas Impresion Serigrafica - Taller De Diseño",
"Sistemas Operativos I",
"Sists. Autom. Manufactura I - Comp. Secc 594",
"Sociedad Humana Y Ecologia",
"Sociologia",
"Solucion Contr. Comerc. Inter. - Clase Tutorial Relaciones Internacionales",
"Taller Integrador",
"Tecnica Terapeutica - Plan Viejo Comp. Secc 537",
"Tecnicas De Expresion E Ilust. - Taller De Diseño",
"Tecnicas De Presentacion",
"Tecno. Hospedaje Ii",
"Tecnologias Emergentes",
"Tenis De Campo - Polid",
"Teo. Psic. Personalidad I",
"Teo. Y Práct. Política Exter.
Teor. Psic. Personalidad Ii",
"Teoria Base De Datos I",
"Teoria Del Color",
"Teoria General Del Estado",
"Teoría De Las Relac. Int. Ii -
Teoría General Del Proceso",
"Terapéutica Integrada",
"Termodinamica - Comp. Secc. 379",
"Termodinámica - Comp. Secc. 378",
"Topografia I",
"Topografia Ii",
"Trans. Sat. Y Fibra Óptica",
"Turismo De Aventura",
"Turismo Rural",
"Turismo Sostenible",
"Técnicas De Producc. Sonora - Lab. De Computo",
"Técnicas Terapéuticas I",
"Unidad Cardio. Y Neuro.
Urbanismo I",
"Urbanismo Ii",
"Variable Compleja",
"Vias De Comunicacion I",
"Vias De Comunicacion Ii",
"Virtual Image - Taller De Diseño De 1:00Pm A 3:40Pm",
"Voleibol - En Polideportivo",
"Xcode E Interface Builder",
"Ética En Salud -
Ética Médica I - Jueves De 10:10 Am 12:50 P.M. Viernes 11:30 Am A 12:50 P.M.
Ética Médica Ii - Lunes, Martes Y Viernes",
"Ética Psicológica"]


# Courses
courses.each_with_index do |c, i|
    Course.create!(id: i, name: c)
end

# Students
(1..1000).each do |n|
    courses = Array.new
    course_count = Course.count - 1
    (1..10).each do |c|
        courses.push(Course.find(rand(course_count)))
    end
    Student.create!(id: n, name: Namey::Generator.new.name, courses: courses)
end

# Teachers
(1..100).each do |n|
    courses = Array.new
    course_count = Course.count - 1
    (1..6).each do |c|
        courses.push(Course.find(rand(course_count)))
    end
    time_order_options = [7,8,10,11,13,14,15,17,18]
    start_time = time_order_options.sample
    end_time = start_time + [2,3,4,5,6].sample
    Teacher.create!(id: n, name: Namey::Generator.new.name, courses: courses, start_time: start_time, end_time: end_time)
end

# Rooms
(1..35).each do |n|
    Room.create!(id: n, name: "R" + n.to_s)
end
